version: '3.9'

services:
  postgres:
    build:
      context: ./db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - travellerpg:/var/lib/postgresql/data

  web:
    build: .
    command: sleep infinity
    ports:
      - 5000:5000
    volumes:
      - .:/traveller
    env_file:
      - ./app.env
    depends_on:
      postgres:
        condition: service_started

volumes:
  travellerpg:
